# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  encoding: utf8
  # port:     <%= ENV.fetch('DB_PORT', '5432') %>
  pool:     <%= ENV.fetch('DB_MAX_THREADS', 5) %>
  host:     <%= ENV.fetch('DB_HOST', 'localhost') %>
  database: <%= ENV.fetch('DB_DATABASE') %>
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  timeout:  5000

development:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE') %>_development

test:
  <<: *default
  database: <%= ENV.fetch('DB_DATABASE') %>_test

production:
  <<: *default